const booking={step:1,frequency:'once',time:'',promo:false};
const qs=new URLSearchParams(location.search),preselect=qs.get('service');
const serviceSelect=document.querySelector('#serviceSelect');
GOCLEAN_SERVICES.forEach(s=>serviceSelect.add(new Option(`${s.name} — ${s.price}`,s.slug)));
if(preselect&&GOCLEAN_SERVICES.some(s=>s.slug===preselect))serviceSelect.value=preselect;
if(qs.get('object'))document.querySelector('#objectType').value=qs.get('object');
if(qs.get('baths'))document.querySelector('#bathrooms').value=qs.get('baths');
if(qs.get('frequency')&&['weekly','biweekly','monthly'].includes(qs.get('frequency'))){booking.frequency=qs.get('frequency');document.querySelectorAll('[data-frequency]').forEach(x=>x.classList.toggle('active',x.dataset.frequency===booking.frequency));}
const objectNames={apartment:'Kvartira',cottage:'Kottej',office:'Ofis',store:'Do‘kon',mall:'Savdo markazi',production:'Ishlab chiqarish',warehouse:'Ombor',building:'Ko‘p qavatli uy',other:'Boshqa'};
const basePrice={general:500000,dry:100000,windows:12000,special:20000,facade:18000,repair:16000,emergency:22000,odor:12000,mold:25000,disinfection:10000};
const money=n=>new Intl.NumberFormat('uz-UZ').format(Math.round(n/1000)*1000)+' so‘m';
function calc(){const service=findService(serviceSelect.value),area=Math.max(1,+document.querySelector('#area').value||1);let total=basePrice[service.bookingType]||20000;if(['windows','special','facade','repair','emergency','odor','mold','disinfection'].includes(service.bookingType))total*=area;else if(service.bookingType==='general')total+=Math.max(0,area-50)*6000;document.querySelectorAll('[data-extra]:checked').forEach(x=>total+=+x.dataset.extra);const discount={once:0,weekly:.15,biweekly:.10,monthly:.05}[booking.frequency];total*=1-discount;if(booking.promo)total*=.95;document.querySelector('#summaryService').textContent=service.name;document.querySelector('#summaryObject').textContent=objectNames[document.querySelector('#objectType').value];document.querySelector('#summaryArea').textContent=area+' m²';document.querySelector('#summaryDuration').textContent='~'+Math.max(2,Math.ceil(area/20))+' soat';document.querySelector('#summaryWorkers').textContent=(area>100?3:area>55?2:1)+' kishi';document.querySelector('#summaryTotal').textContent=money(total);document.querySelector('#summaryExtras').innerHTML=[...document.querySelectorAll('[data-extra]:checked')].map(x=>`<span>+ ${x.parentElement.querySelector('b').textContent}</span>`).join('');return total}
function showStep(n){booking.step=n;document.querySelectorAll('.checkout-step').forEach(x=>x.classList.toggle('active',+x.dataset.step===n));document.querySelectorAll('[data-pill]').forEach(x=>x.classList.toggle('active',+x.dataset.pill<=n));scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('.next-step').forEach(b=>b.onclick=()=>{if(+b.dataset.next===3){const req=['customerName','customerPhone','address'];if(req.some(id=>!document.querySelector('#'+id).value.trim())){alert('Kontakt va manzil maydonlarini to‘ldiring');return}}if(+b.dataset.next===4&&(!document.querySelector('#date').value||!booking.time)){alert('Sana va vaqtni tanlang');return}showStep(+b.dataset.next)});
document.querySelectorAll('.back-step').forEach(b=>b.onclick=()=>showStep(+b.dataset.back));
document.querySelectorAll('[data-frequency]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-frequency]').forEach(x=>x.classList.remove('active'));b.classList.add('active');booking.frequency=b.dataset.frequency;calc()});
document.querySelectorAll('[data-time]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-time]').forEach(x=>x.classList.remove('active'));b.classList.add('active');booking.time=b.dataset.time});
['objectType','serviceSelect','area','bathrooms'].forEach(id=>document.querySelector('#'+id).addEventListener('input',calc));document.querySelectorAll('[data-extra]').forEach(x=>x.onchange=calc);
document.querySelector('#applyPromo').onclick=()=>{if(document.querySelector('#promo').value.trim().toUpperCase()==='GO5'){booking.promo=true;document.querySelector('#promoMessage').textContent='GO5: 5% chegirma qo‘llandi';calc()}else document.querySelector('#promoMessage').textContent='Promokod topilmadi'};
document.querySelector('#checkoutForm').onsubmit=e=>{e.preventDefault();const order={id:'GC-'+Date.now().toString().slice(-6),service:serviceSelect.value,object:document.querySelector('#objectType').value,area:document.querySelector('#area').value,name:document.querySelector('#customerName').value,phone:document.querySelector('#customerPhone').value,address:document.querySelector('#address').value,date:document.querySelector('#date').value,time:booking.time,frequency:booking.frequency,total:calc(),payment:new FormData(e.target).get('payment')};const orders=JSON.parse(localStorage.getItem('gocleanOrders')||'[]');orders.push(order);localStorage.setItem('gocleanOrders',JSON.stringify(orders));document.querySelector('#orderNumber').textContent=`Buyurtma raqami: ${order.id}`;document.querySelector('#successDialog').showModal()};
document.querySelector('#date').min=new Date().toISOString().split('T')[0];calc();
