(function(){
  const telegramIcon=`<svg class="telegram-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M21.7 3.2 18.6 20c-.2 1.2-.9 1.5-1.9.9l-4.7-3.5-2.3 2.2c-.3.3-.5.5-1 .5l.3-4.8 8.8-8c.4-.3-.1-.5-.6-.2L6.3 14 1.6 12.5c-1-.3-1-1 .2-1.5L20.1 4c.9-.3 1.8.2 1.6 1.2Z"/></svg>`;
  const drawer=`<aside class="mobile-drawer" id="mobileDrawer" aria-hidden="true"><div class="drawer-top"><a href="tel:+998977071515">☎</a><a href="https://t.me/gocleanuz" aria-label="Telegram">${telegramIcon}</a><button class="drawer-close" type="button" aria-label="Yopish">×</button></div><div class="drawer-switch" role="tablist"><button class="active" type="button" data-menu-mode="home">Uy uchun</button><button type="button" data-menu-mode="business">Biznes uchun</button></div><div class="drawer-context"><span>⌖</span><b>Toshkent</b><small>Har kuni 08:00–21:00</small></div><nav class="drawer-links" data-menu-panel="home"><a href="services.html"><i>✦</i><span><b>Barcha xizmatlar</b><small>14 turdagi professional tozalash</small></span></a><a href="service.html?slug=general-cleaning"><i>⌂</i><span><b>General tozalash</b><small>Uy va hovli uchun</small></span></a><a href="service.html?slug=furniture-cleaning"><i>▱</i><span><b>Mebel kimyoviy tozalash</b><small>Divan, kreslo va matras</small></span></a><a href="service.html?slug=window-cleaning"><i>▦</i><span><b>Oyna yuvish</b><small>Deraza, vitrina va romlar</small></span></a><a href="booking.html"><i>＋</i><span><b>Buyurtma berish</b><small>Vaqt va xizmatni tanlang</small></span></a></nav><nav class="drawer-links" data-menu-panel="business" hidden><a href="business.html"><i>▦</i><span><b>Biznes uchun</b><small>Korporativ yechimlar</small></span></a><a href="office-cleaning.html"><i>▥</i><span><b>Ofis tozalash</b><small>Muntazam yoki bir martalik</small></span></a><a href="service.html?slug=facade-cleaning"><i>▤</i><span><b>Fasad va vitrina</b><small>Balandlikdagi ishlar</small></span></a><a href="service.html?slug=marble-cleaning"><i>◇</i><span><b>Pol va marmar</b><small>Tozalash va jilolash</small></span></a><a href="service.html?slug=disinfection"><i>✚</i><span><b>Dezinfeksiya</b><small>Tijorat obyektlari uchun</small></span></a></nav><a class="drawer-cta" data-menu-cta href="booking.html">Uy tozalashni buyurtma qilish →</a><div class="drawer-meta"><a href="auth.html">Profil</a><a href="contact.html">Kontaktlar</a><a href="legal.html?doc=privacy">Maxfiylik</a></div></aside><button class="drawer-backdrop" type="button" aria-label="Menyuni yopish"></button>`;
  const header=`<div class="announcement"><span>Toshkent bo‘ylab har kuni 08:00–21:00</span><a href="tel:+998977071515">+998 97 707 15 15</a></div><header class="site-header"><div class="nav-wrap container"><a class="brand" href="index.html"><span class="brand-mark"><svg viewBox="0 0 48 48"><path d="M14 30c9 0 16-7 16-16 7 6 10 13 7 20-3 7-12 11-20 8-5-2-8-6-9-11 2 0 4-1 6-1Z"/></svg></span><span>Go<span>clean</span><small>.uz</small></span></a><nav id="mainNav" class="main-nav"><a href="services.html">Xizmatlar</a><a href="office-cleaning.html">Ofis tozalash</a><a href="business.html">Biznes uchun</a><a href="contact.html">Kontaktlar</a></nav><div class="nav-actions"><a class="profile-link" href="auth.html" aria-label="Profil">◯</a><a class="outline-button desktop-cta" href="booking.html">Buyurtma berish</a><button class="menu-button" id="menuButton" type="button" aria-expanded="false" aria-controls="mobileDrawer" aria-label="Menyuni ochish"><span></span><span></span><span></span></button></div></div></header>${drawer}`;
  const footer=`<footer><div class="container footer-grid"><div><a class="brand footer-brand" href="index.html"><span class="brand-mark"><svg viewBox="0 0 48 48"><path d="M14 30c9 0 16-7 16-16 7 6 10 13 7 20-3 7-12 11-20 8-5-2-8-6-9-11 2 0 4-1 6-1Z"/></svg></span><span>Go<span>clean</span><small>.uz</small></span></a><p>Uy va biznes uchun professional tozalash xizmati.</p></div><div><b>Xizmatlar</b><a href="service.html?slug=general-cleaning">General tozalash</a><a href="service.html?slug=furniture-cleaning">Mebel tozalash</a><a href="service.html?slug=window-cleaning">Oyna yuvish</a></div><div><b>Kompaniya</b><a href="business.html">Biznes uchun</a><a href="contact.html">Kontaktlar</a><a href="auth.html">Shaxsiy kabinet</a></div><div><b>Bog‘lanish</b><a href="tel:+998977071515">+998 97 707 15 15</a><a href="https://t.me/gocleanuz">Telegram</a><a href="mailto:hello@goclean.uz">hello@goclean.uz</a><span>Toshkent, O‘zbekiston</span></div></div><div class="container footer-bottom"><span>© 2026 Goclean.uz</span><div><a href="legal.html?doc=privacy">Maxfiylik siyosati</a><a href="legal.html?doc=terms">Foydalanish shartlari</a></div></div></footer>`;
  document.querySelectorAll('[data-site-header]').forEach(el=>el.innerHTML=header);
  document.querySelectorAll('[data-site-footer]').forEach(el=>el.innerHTML=footer);
  if(!document.querySelector('#mobileDrawer'))document.querySelector('.site-header')?.insertAdjacentHTML('afterend',drawer);
  function initDrawer(){
    const menu=document.querySelector('#menuButton'),drawer=document.querySelector('#mobileDrawer'),backdrop=document.querySelector('.drawer-backdrop');if(!menu||!drawer)return;
    const setOpen=open=>{drawer.classList.toggle('open',open);backdrop?.classList.toggle('open',open);drawer.setAttribute('aria-hidden',String(!open));menu.setAttribute('aria-expanded',String(open));document.body.classList.toggle('drawer-open',open)};
    menu.addEventListener('click',()=>setOpen(!drawer.classList.contains('open')));drawer.querySelector('.drawer-close')?.addEventListener('click',()=>setOpen(false));backdrop?.addEventListener('click',()=>setOpen(false));
    drawer.querySelectorAll('[data-menu-mode]').forEach(btn=>btn.addEventListener('click',()=>{const mode=btn.dataset.menuMode;drawer.querySelectorAll('[data-menu-mode]').forEach(x=>x.classList.toggle('active',x===btn));drawer.querySelectorAll('[data-menu-panel]').forEach(p=>p.hidden=p.dataset.menuPanel!==mode);const cta=drawer.querySelector('[data-menu-cta]');cta.href=mode==='home'?'booking.html':'business-request.html';cta.textContent=mode==='home'?'Uy tozalashni buyurtma qilish →':'Biznes uchun hisob olish →'}));
  }
  initDrawer();window.initGoCleanDrawer=initDrawer;
})();
